INSERT INTO public.test_forms (
  serial, patient_name, age, gender, phone, email,
  referred_by, doctor_phone, institution,
  date_collected, nature_of_specimen, examination_required,
  tests_requested, clinical_notes, bill, status, completed_at, results
) VALUES (
  'MV-2026-00999',
  'Demo Patient Test',
  35, 'Male', '+234 800 000 0000', 'demo@medvicgoodhealth.com',
  'Dr. Demo Reviewer', '+234 801 000 0000', 'Medvic Goodhealth Demo Clinic',
  '2026-04-20T08:00:00Z', 'Whole Blood, Serum, Urine, Semen',
  'Full Comprehensive Panel (Demo)',
  ARRAY['Full Blood Count (FBC)','Chemical Pathology Panel','Widal Test','Fertility Profile','Thyroid Function Test','Urinalysis','Urine Microscopy','Sensitivity','Semen Analysis','Other Investigations'],
  'Mock patient — used to verify end-to-end report rendering and PDF download.',
  'Patient', 'Completed', '2026-04-20T15:30:00Z',
  '{
    "hb":"14.2","pcv":"42","wbc":"6.8","neutrophils":"60","lymphocyte":"32","monocyte":"5","eosinophil":"2","basophil":"1",
    "filmReport":"Normochromic, normocytic red cells. No abnormal cells seen.",
    "malariaParasite":"Not Seen","platelets":"245","esr":"6","prothrombinTime":"13",
    "directCombs":"Negative","indirectCombs":"Negative","bloodGroup":"O+","genotype":"AA",
    "hepatitisScreening":"Non-Reactive","retroviralScreening":"Non-Reactive","vdrl":"Non-Reactive","pregnancy":"Negative",
    "haemOthers":"All haematology indices within normal limits.",
    "fbs":"5.1","rbs":"6.2","tBilirubin":"10.4","cBilirubin":"3.1","alkPhos":"88","ast":"24","alt":"28",
    "totalProtein":"72","albumin":"42","sodium":"139","potassium":"4.3","chloride":"104","bicarbonate":"26",
    "calcium":"2.4","urea":"4.6","creatinine":"86","uricAcid":"310",
    "cholesterol":"4.6","triglyceride":"1.2","hdl":"1.3","ldl":"2.8",
    "salTyphiO":"1/40","salTyphiH":"1/40","salParaAO":"1/20","salParaAH":"1/20","salParaBO":"1/20","salParaBH":"1/20","salParaCO":"1/20","salParaCH":"1/20",
    "lh":"4.5","fsh":"5.2","prolactin":"8.4","progesterone":"0.8","estradiol":"35","testosterone":"5.6",
    "t4":"8.1","t3":"1.4","tsh":"2.1","psa":"1.2","cortisol":"14",
    "appearance":"Clear, Straw-coloured","ph":"6.0","specificGravity":"1.020",
    "uProtein":"Negative","nitrite":"Negative","uGlucose":"Negative","ketones":"Negative",
    "urobilinogen":"Normal","uBilirubin":"Negative","ascorbicAcid":"Negative","leukocytes":"Negative",
    "epithelialCells":"Few","mWbc":"1-2/hpf","mRbc":"Nil","yeastCells":"Nil","cast":"Nil","crystal":"Nil","bacteriaCells":"Nil",
    "microscopyRemarks":"No significant findings.",
    "abx_pefloxacin":"S (Sensitive)","abx_gentamycin":"S (Sensitive)","abx_ampiclox":"R (Resistant)",
    "abx_zinnacef":"S (Sensitive)","abx_amoxicillin":"I (Intermediate)","abx_rocephin":"S (Sensitive)",
    "abx_ciprofloxacin":"S (Sensitive)","abx_azithromycin":"S (Sensitive)","abx_levofloxacin":"S (Sensitive)",
    "abx_erythromycin":"R (Resistant)","abx_ofloxacin":"S (Sensitive)","abx_augmentin":"I (Intermediate)",
    "abx_paflacine":"S (Sensitive)","abx_ceftazidine":"S (Sensitive)","abx_cefalexin":"R (Resistant)",
    "abx_ceftriaxone":"S (Sensitive)","abx_streptomycin":"I (Intermediate)",
    "timeProduced":"08:00","timeSubmitted":"08:20","timeExamined":"09:00",
    "volume":"3.2","colour":"Greyish-white","consistency":"Viscous, liquefies in 25 mins",
    "count":"68","activeMotile":"60","sluggish":"25","nonMotile":"15",
    "semenOthers":"Normal morphology. No agglutination observed.","isolates":"No growth after 48 hours.",
    "bloodCultureIsolates":"No growth after 5 days incubation.",
    "hPylori":"Negative","fob":"Negative","afb":"Negative","microfilaria":"Not Seen",
    "mantoux":"5mm induration","chlamydia":"Negative"
  }'::jsonb
)
ON CONFLICT (serial) DO UPDATE SET
  results = EXCLUDED.results,
  status = EXCLUDED.status,
  completed_at = EXCLUDED.completed_at,
  updated_at = now();